### ISSUE TITLE
Can not detect which host are controller-node or compute-node etc.

### ISSUE THREAD

**Issue by TsutomuNakamura** [tsuna-server/build-server-ansible#1]
There are no way to detect which host have which roles so far.
To be able to it, format of the config file should be changed.

https://github.com/tsuna-server/build-server-ansible/blob/1476e1f/group_vars/all_dev

```
eg)
  hosts:
    # Define IP addresses in management
    dev-private-router01: 192.168.2.1
    dev-compute01: 192.168.2.11
    dev-compute02: 192.168.2.12
    dev-compute03: 192.168.2.13

  ↓  ↓  ↓  ↓  ↓

  hosts:
    controllers:
      - name: dev-private-router01
        ip: 192.168.2.1
    computes:
      - name: dev-compute01
        ip: 192.168.2.11
      - name: dev-compute02
        ip: 192.168.2.12
      - name: dev-compute03
        ip: 192.168.2.13
```
