### ISSUE TITLE
Change a structure of variables of hosts

### ISSUE THREAD

**Issue by TsutomuNakamura** [tsuna-server/build-server-ansible#41]
A variable of the hosts in `group_vars/all` should be changed a its structure from ...
```
group_vars:
  hosts:
    controllers:
      - name: dev-private-router01.openstack.example.com
        ip: 172.29.0.1
    computes:
      - name: dev-compute01.openstack.example.com
        ip: 172.29.1.11
      - name: dev-compute02.openstack.example.com
        ip: 172.29.1.12
      - name: dev-compute03.openstack.example.com
        ip: 172.29.1.13
```

to ...

```
group_vars:
  hosts:
    controllers:
      - names: ["dev-private-router01.openstack.example.com", "dev-private-router01"]
        ip: 172.29.0.1
    computes:
      - names: ["dev-compute01.openstack.example.com", "dev-compute01"]
        ip: 172.29.1.11
      - namea: ["dev-compute02.openstack.example.com", "dev-compute02"]
        ip: 172.29.1.12
      - names: ["dev-compute03.openstack.example.com", "dev-compute03"]
        ip: 172.29.1.13
```
.

Changing the structure makes easier to find an IP from the variable `inventory_hostname`.
