### ISSUE TITLE
`apt upgrade` in the early point in the playbooks should retry if it was failed.

### ISSUE THREAD

**Issue by TsutomuNakamura** [tsuna-server/build-server-ansible#52]
This Ansible playbooks will be used as part of other Ansible playbooks. Instructions of apt should not be stopped if it was failed only one time.

* ex) 
```
- name: Upgrade all current packages
  apt:
    upgrade: full
    update_cache: yes
  register: apt_result    # <- Should be added
  retries: 360    # <- Should be added
  delay: 5    # <- Should be added
  until: apt_result is success    # <- Should be added
```
