### ISSUE TITLE
interface_driver in l3_agent.ini should be specified for OVN Neutron driver

### ISSUE THREAD

**Issue by TsutomuNakamura** [tsuna-server/build-server-ansible#60]
Interface driver should be specified in l3_agent.ini like below.

* /etc/neutron/l3_agent.ini
```
[DEFAULT]
# ...
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver
```

Neutron will output errors if `interface_driver` was not specified when we use OVN Neutron driver.

**Comment by TsutomuNakamura** [comment]
Compute nodes are recovered but a controller node is still hanging up.

**Comment by TsutomuNakamura** [comment]
Cause of the issue might be in a role `test_env`.

## Test
* site.yml
```
#- import_playbook: commons.yml
#- import_playbook: controllers.yml
#- import_playbook: computes.yml
#- import_playbook: controllers_discover_hosts.yml
- import_playbook: controllers_create_example_instances.yml
```

* roles/test_env/tasks/main.yml
```
- name: Determin which network driver will be used. Linux Bridge or OVN are only supported so far.
  set_fact:
    network_plugin: "{% if 'network' not in group_vars.openstack or 'plugin' not in group_vars.openstack.network or 'Linux Bridge' == group_vars.openstack.network.plugin %}Linux Bridge{% else %}{{ group_vars.openstack.network.plugin }}{% endif %}"

# Pre-bridge-configuration for OVN
- name: Include configure_bridge_for_ovn/main.yml
  include: configure_bridge_for_ovn/main.yml
  when: "'OVN' == network_plugin"

#- name: Block create test env on controller node
#  block:
#   ... comment out
#  when: "'controllers' in group_names"
```

**Comment by TsutomuNakamura** [comment]
## Test 05

* roles/test_env_tasks/create_example_router/do_create_router.yml
```
- name: Block of creating router
  block:
    - name: Create a router
      ansible.builtin.command:
        argv: ["openstack", "router", "create", "{{ router.name }}"]
      register: result

    - name: Print the result of creating router
      ansible.builtin.debug:
        msg: "{{ result.stdout.split('\n') }}"

    - name: Set a gateway to the router
      ansible.builtin.command:
        argv: ["openstack", "router", "set", "--external-gateway", "{{ router.external_gateway }}", "{{ router.name }}"]
      register: result

    - name: Print the result of setting a gateway
      ansible.builtin.debug:
        msg: "{{ result.stdout.split('\n') }}"

    # ......
  when: result_of_checking_router.rc == 0
```

It makes hanging up.

**Comment by TsutomuNakamura** [comment]
Restarting controller node after ...
```
    - name: Set a gateway to the router
      ansible.builtin.command:
        argv: ["openstack", "router", "set", "--external-gateway", "{{ router.external_gateway }}", "{{ router.name }}"]
      register: result
```
will solve hanging up.
